from animalTripleWriter import animalTripleWriter
from CGFTripleWriter import CGFTripleWriter
from enviroTripleWriter import enviroTripleWriter
from humanTripleWriter import humanTripleWriter
from isolateTripleWriter import isolateTripleWriter
from util import popVals
from drugResistanceWriter import drugResistanceWriter