from createAnimalTriple import createAnimalTriple
from createCGFTriple import createCGFTriple
from createEnviroTriple import createEnviroTriple
from createHumanTriple import createHumanTriple
from createIsolateTriple import createIsolateTriple
from util import popVals
from createDrugResistanceTriple import createDrugResistanceTriple